# Generated by Django 4.2.7 on 2026-03-27 06:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id_secteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_secteur', models.CharField(max_length=100, verbose_name='Nom du secteur')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
                'db_table': 'secteur',
                'ordering': ['nom_secteur'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneSdau',
            fields=[
                ('id_zone', models.AutoField(primary_key=True, serialize=False)),
                ('zone_sdau', models.CharField(choices=[('Zone à urbaniser en priorité', 'Zone à urbaniser en priorité'), ('Zone de recasement', 'Zone de recasement'), ("Zone d'activité diverse à créer", "Zone d'activité diverse à créer"), ('Zone résidentielle de densification à viabiliser', 'Zone résidentielle de densification à viabiliser'), ('Zone de végétation naturelle à restaurer', 'Zone de végétation naturelle à restaurer'), ("Zone d'habitat planifier à créer", "Zone d'habitat planifier à créer"), ('Zone de requalification urbaine', 'Zone de requalification urbaine'), ("zone d'habitat planifieée à viabiliser et à densif", "zone d'habitat planifieée à viabiliser et à densif"), ("Zone d'extension de l'habitat", "Zone d'extension de l'habitat"), ('Zone de promotion touristique à créer', 'Zone de promotion touristique à créer'), ('Zone inondable non aedificandi', 'Zone inondable non aedificandi'), ("Zone d'affleurement granitique", "Zone d'affleurement granitique"), ('Zone de formation professionnelle', 'Zone de formation professionnelle'), ("Zone d'activité admistrative et commerciale à crée", "Zone d'activité admistrative et commerciale à crée"), ('Parc urbain à créer', 'Parc urbain à créer'), ('Zone de réserve foncière à créer', 'Zone de réserve foncière à créer'), ('Zone résidentielle à structurer et viabiliser', 'Zone résidentielle à structurer et viabiliser'), ('Zone industrielle à créer', 'Zone industrielle à créer'), ('zone de restructuration urbaine', 'zone de restructuration urbaine'), ('Zone administrative à réhabiliter', 'Zone administrative à réhabiliter'), ("Zone bleue de barrage et cours d'eau", "Zone bleue de barrage et cours d'eau"), ('Zone de rénovation du bâti', 'Zone de rénovation du bâti'), ('Zone agropastorale familiale à conserver', 'Zone agropastorale familiale à conserver'), ('Zone commerciale à aménager', 'Zone commerciale à aménager'), ("Zone d'habitat rural à conserver", "Zone d'habitat rural à conserver")], max_length=200)),
                ('aire_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_zone', models.CharField(choices=[('Habitat', 'Habitat'), ('Activités', 'Activités'), ('Équipements', 'Équipements'), ('Naturelle', 'Naturelle'), ('Espaces verts', 'Espaces verts'), ('Agricole/pastoralisme', 'Agricole/pastoralisme'), ('Touristique', 'Touristique'), ('Réserve foncière', 'Réserve foncière')], max_length=100)),
                ('statut_amenagement', models.CharField(choices=[('À créer', 'À créer'), ('À viabiliser', 'À viabiliser'), ('À aménager', 'À aménager'), ('À réhabiliter', 'À réhabiliter'), ('À restructurer', 'À restructurer'), ('À requalifier', 'À requalifier'), ('À restaurer', 'À restaurer'), ('À conserver', 'À conserver'), ('À protéger', 'À protéger')], max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'zone_sdau',
                'ordering': ['zone_sdau'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_user', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire'), ('consultation', 'Consultation')], default='consultation', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UtilisateurZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_zone', models.ForeignKey(db_column='id_zone', on_delete=django.db.models.deletion.CASCADE, to='sdau.zonesdau')),
            ],
            options={
                'db_table': 'utilisateur_zone',
                'unique_together': {('id_user', 'id_zone')},
            },
        ),
        migrations.CreateModel(
            name='SecteurZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_secteur', models.ForeignKey(db_column='id_secteur', on_delete=django.db.models.deletion.CASCADE, to='sdau.secteur')),
                ('id_zone', models.ForeignKey(db_column='id_zone', on_delete=django.db.models.deletion.CASCADE, to='sdau.zonesdau')),
            ],
            options={
                'db_table': 'secteur_zone',
                'unique_together': {('id_secteur', 'id_zone')},
            },
        ),
    ]
